
package javaapplication30;

import javax.swing.JButton;

public class Pantalla extends javax.swing.JFrame {
String preguntas[][] = new String[28][3];
Metodos MM = new Metodos();
int numero = 0;
int correctas=0;
int erroneas=0;
int pasaste=0;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setExtendedState(this.getExtendedState()|Pantalla.MAXIMIZED_BOTH);
        this.btnNADA.setVisible(false);
         this.LogoCentro1.setVisible(false);
        this.LogoArriba.setVisible(false);
        this.btnFin.setVisible(false);
        this.lblpregunta.setVisible(false);
        this.jLabel13.setVisible(false);
        this.txtRespuesta.setVisible(false);
        this.jLabel2.setVisible(false);
        this.btnResponder.setVisible(false);
        this.btnPasaPalabra.setVisible(false);
        this.btnTiempo.setText("180");
        preguntas[0][0] = "Letra A: Aro de metal u otra materia que se lleva en los dedos de la mano";
        preguntas[0][1] = "Anillo";       
        preguntas[1][0] = "Letra B: Prenda de vestir holgada, con mangas y abierta, se usa para estar por casa";
        preguntas[1][1] = "Bata";        
        preguntas[2][0] = "Letra C: Cordón de alambres trenzados, generalmente de cobre.";
        preguntas[2][1] = "Cable";      
        preguntas[3][0] = "Letra D: partes de la cabeza de ajo, separadas por su tela y cáscara";
        preguntas[3][1] = "Dientes";
        
        preguntas[4][0] = "Letra E: Poner derecho lo que está...";
        preguntas[4][1] = "Enderezar";
                
        preguntas[5][0] = "Letra F: Instrumento musical de viento, en forma de tubo";
        preguntas[5][1] = "Flauta"; 

        preguntas[6][0] = "Letra G: Animal que hace Miau";
        preguntas[6][1] = "Gato"; 

        preguntas[7][0] = "Letra H: Dícese del Agua Congelada";
        preguntas[7][1] = "Hielo";

        preguntas[8][0] = "Letra I: País Europeo conocido por su forma de bota";
        preguntas[8][1] = "Italia";
        
        preguntas[9][0] = "Letra J: Persona de corta edad";
        preguntas[9][1] = "Joven";
        
        preguntas[10][0] = "Letra K: Unidad de medida de peso";
        preguntas[10][1] = "Kilo";       

        preguntas[11][0] = "Letra L: Único satélite natural de la tierra";
        preguntas[11][1] = "Luna";

        preguntas[12][0] = "Letra M: Lazo de cintas";
        preguntas[12][1] = "Moño";

        preguntas[13][0] = "Letra N: Lugar donde habitan las aves";
        preguntas[13][1] = "Nido";

        preguntas[14][0] = "Contiene Ñ: Elemento para pescar";
        preguntas[14][1] = "Caña";

        preguntas[15][0] = "Letra O: Animal que duerme durante el invierno";
        preguntas[15][1] = "Oso";

        preguntas[16][0] = "Letra P: Pedazo de tela pequeño para los resfríos";
        preguntas[16][1] = "Pañuelo";

        preguntas[17][0] = "Letra Q: Producto Lácteo";
        preguntas[17][1] = "Queso";

        preguntas[18][0] = "Letra R: Rueda giratoria utilizada en juegos de azar";
        preguntas[18][1] = "Ruleta";

        preguntas[19][0] = "Letra S: Respuesta Afirmativa";
        preguntas[19][1] = "SI"; 
        
        preguntas[20][0] = "Letra T: Parte trasera de un zapato";
        preguntas[20][1] = "Taco";        
        
        preguntas[21][0] = "Letra U: Fruto obtenido en un Viñedo";
        preguntas[21][1] = "Uva";  
 
        preguntas[22][0] = "Letra V: Recipiente para tomar algún tipo de líquido";
        preguntas[22][1] = "Vaso";
        
        preguntas[23][0] = "Contiene W: Fruta Tropical color verde en su interior";
        preguntas[23][1] = "Kiwi";
        
        preguntas[24][0] = "Letra X: Cantante Brasilera de los Bajitos";
        preguntas[24][1] = "xuxa";

        preguntas[25][0] = "Letra Y: Banco metálico donde trabaja el herrero";
        preguntas[25][1] = "Yunque";
        
        preguntas[26][0] = "Letra Z: Calzado utilizado en la actualidad";
        preguntas[26][1] = "Zapato";               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblpregunta = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnTiempo = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnD = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnRojo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnF = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnG = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnResponder = new javax.swing.JButton();
        btnPasaPalabra = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnI = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnJ = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnK = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnL = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnM = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnN = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnÑ = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnO = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnP = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btnQ = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        btnR = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnS = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnT = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        btnU = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        btnV = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        btnW = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        btnX = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        btnY = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnZ = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        LogoArriba = new javax.swing.JLabel();
        LogoCentro1 = new javax.swing.JLabel();
        LogoCentro = new javax.swing.JLabel();
        lblFaltante = new javax.swing.JLabel();
        lblCorrectas = new javax.swing.JLabel();
        lblPasaste = new javax.swing.JLabel();
        lblErronea = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btnNADA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(550, 30, 42, 50);

        lblpregunta.setBackground(new java.awt.Color(0, 51, 102));
        lblpregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblpregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpregunta.setText("Pregunta");
        lblpregunta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblpregunta.setOpaque(true);
        jPanel1.add(lblpregunta);
        lblpregunta.setBounds(0, 660, 1360, 40);

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/botonnuevo.png"))); // NOI18N
        btnIniciar.setBorder(null);
        btnIniciar.setBorderPainted(false);
        btnIniciar.setContentAreaFilled(false);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar);
        btnIniciar.setBounds(1040, 400, 250, 80);

        btnA.setBackground(new java.awt.Color(51, 255, 204));
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnA.setBorder(null);
        btnA.setBorderPainted(false);
        btnA.setContentAreaFilled(false);
        btnA.setMaximumSize(new java.awt.Dimension(60, 60));
        btnA.setMinimumSize(new java.awt.Dimension(60, 60));
        btnA.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnA);
        btnA.setBounds(540, 30, 60, 60);

        btnTiempo.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        btnTiempo.setText("180");
        btnTiempo.setBorder(null);
        btnTiempo.setBorderPainted(false);
        btnTiempo.setContentAreaFilled(false);
        btnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiempoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTiempo);
        btnTiempo.setBounds(1080, 240, 170, 130);

        btnFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/botonfin.png"))); // NOI18N
        btnFin.setBorder(null);
        btnFin.setBorderPainted(false);
        btnFin.setContentAreaFilled(false);
        btnFin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        jPanel1.add(btnFin);
        btnFin.setBounds(1050, 120, 220, 60);

        jLabel5.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("C");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(680, 60, 42, 60);

        btnC.setBackground(new java.awt.Color(51, 255, 204));
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnC.setBorder(null);
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setMaximumSize(new java.awt.Dimension(60, 60));
        btnC.setMinimumSize(new java.awt.Dimension(60, 60));
        btnC.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnC);
        btnC.setBounds(670, 60, 60, 60);

        jLabel6.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("B");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(620, 50, 42, 40);

        btnB.setBackground(new java.awt.Color(51, 255, 204));
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnB.setBorder(null);
        btnB.setBorderPainted(false);
        btnB.setContentAreaFilled(false);
        btnB.setMaximumSize(new java.awt.Dimension(60, 60));
        btnB.setMinimumSize(new java.awt.Dimension(60, 60));
        btnB.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnB);
        btnB.setBounds(610, 40, 60, 60);

        jLabel7.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("D");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(730, 90, 60, 60);

        btnD.setBackground(new java.awt.Color(51, 255, 204));
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnD.setBorder(null);
        btnD.setBorderPainted(false);
        btnD.setContentAreaFilled(false);
        btnD.setMaximumSize(new java.awt.Dimension(60, 60));
        btnD.setMinimumSize(new java.awt.Dimension(60, 60));
        btnD.setPreferredSize(new java.awt.Dimension(60, 60));
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        jPanel1.add(btnD);
        btnD.setBounds(730, 90, 60, 60);

        jLabel8.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(790, 140, 38, 60);

        btnRojo.setBackground(new java.awt.Color(51, 255, 204));
        btnRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/reloj.png"))); // NOI18N
        btnRojo.setBorder(null);
        btnRojo.setBorderPainted(false);
        btnRojo.setContentAreaFilled(false);
        btnRojo.setMaximumSize(new java.awt.Dimension(60, 60));
        btnRojo.setMinimumSize(new java.awt.Dimension(60, 60));
        btnRojo.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnRojo);
        btnRojo.setBounds(1060, 190, 220, 220);

        jLabel9.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("F");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(820, 190, 60, 60);

        btnF.setBackground(new java.awt.Color(51, 255, 204));
        btnF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnF.setBorder(null);
        btnF.setBorderPainted(false);
        btnF.setContentAreaFilled(false);
        btnF.setMaximumSize(new java.awt.Dimension(60, 60));
        btnF.setMinimumSize(new java.awt.Dimension(60, 60));
        btnF.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnF);
        btnF.setBounds(820, 190, 60, 60);

        jLabel10.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("G");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(850, 270, 50, 40);

        btnG.setBackground(new java.awt.Color(51, 255, 204));
        btnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnG.setBorder(null);
        btnG.setBorderPainted(false);
        btnG.setContentAreaFilled(false);
        btnG.setMaximumSize(new java.awt.Dimension(60, 60));
        btnG.setMinimumSize(new java.awt.Dimension(60, 60));
        btnG.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnG);
        btnG.setBounds(840, 260, 60, 60);

        jLabel11.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("H");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(860, 330, 43, 40);

        btnH.setBackground(new java.awt.Color(51, 255, 204));
        btnH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnH.setBorder(null);
        btnH.setBorderPainted(false);
        btnH.setContentAreaFilled(false);
        btnH.setMaximumSize(new java.awt.Dimension(60, 60));
        btnH.setMinimumSize(new java.awt.Dimension(60, 60));
        btnH.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnH);
        btnH.setBounds(850, 320, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/ecualizador.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 310, 70);

        txtRespuesta.setBackground(new java.awt.Color(0, 255, 255));
        txtRespuesta.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        txtRespuesta.setText("Tu respuesta aquí...");
        txtRespuesta.setBorder(null);
        txtRespuesta.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRespuesta.setOpaque(false);
        txtRespuesta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRespuestaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRespuestaFocusLost(evt);
            }
        });
        jPanel1.add(txtRespuesta);
        txtRespuesta.setBounds(370, 290, 600, 70);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("__________________________________________________________________________________________________");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 340, 800, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("|");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(350, 290, 18, 70);

        btnResponder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/btnresponder.png"))); // NOI18N
        btnResponder.setBorder(null);
        btnResponder.setBorderPainted(false);
        btnResponder.setContentAreaFilled(false);
        btnResponder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderActionPerformed(evt);
            }
        });
        jPanel1.add(btnResponder);
        btnResponder.setBounds(350, 360, 220, 60);

        btnPasaPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/btnpasa.png"))); // NOI18N
        btnPasaPalabra.setBorder(null);
        btnPasaPalabra.setBorderPainted(false);
        btnPasaPalabra.setContentAreaFilled(false);
        btnPasaPalabra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasaPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasaPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(btnPasaPalabra);
        btnPasaPalabra.setBounds(620, 360, 210, 60);

        jLabel14.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("I");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(830, 400, 60, 40);

        btnI.setBackground(new java.awt.Color(51, 255, 204));
        btnI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnI.setBorder(null);
        btnI.setBorderPainted(false);
        btnI.setContentAreaFilled(false);
        btnI.setMaximumSize(new java.awt.Dimension(60, 60));
        btnI.setMinimumSize(new java.awt.Dimension(60, 60));
        btnI.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnI);
        btnI.setBounds(830, 390, 60, 60);

        jLabel15.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("J");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(810, 450, 60, 60);

        btnJ.setBackground(new java.awt.Color(51, 255, 204));
        btnJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnJ.setBorder(null);
        btnJ.setBorderPainted(false);
        btnJ.setContentAreaFilled(false);
        btnJ.setMaximumSize(new java.awt.Dimension(60, 60));
        btnJ.setMinimumSize(new java.awt.Dimension(60, 60));
        btnJ.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnJ);
        btnJ.setBounds(810, 450, 60, 60);

        jLabel16.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("K");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(780, 510, 60, 40);

        btnK.setBackground(new java.awt.Color(51, 255, 204));
        btnK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnK.setBorder(null);
        btnK.setBorderPainted(false);
        btnK.setContentAreaFilled(false);
        btnK.setMaximumSize(new java.awt.Dimension(60, 60));
        btnK.setMinimumSize(new java.awt.Dimension(60, 60));
        btnK.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnK);
        btnK.setBounds(780, 500, 60, 60);

        jLabel17.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("L");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(740, 560, 50, 40);

        btnL.setBackground(new java.awt.Color(51, 255, 204));
        btnL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnL.setBorder(null);
        btnL.setBorderPainted(false);
        btnL.setContentAreaFilled(false);
        btnL.setMaximumSize(new java.awt.Dimension(60, 60));
        btnL.setMinimumSize(new java.awt.Dimension(60, 60));
        btnL.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnL);
        btnL.setBounds(730, 550, 60, 60);

        jLabel18.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("M");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(680, 590, 60, 40);

        btnM.setBackground(new java.awt.Color(51, 255, 204));
        btnM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnM.setBorder(null);
        btnM.setBorderPainted(false);
        btnM.setContentAreaFilled(false);
        btnM.setMaximumSize(new java.awt.Dimension(60, 60));
        btnM.setMinimumSize(new java.awt.Dimension(60, 60));
        btnM.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnM);
        btnM.setBounds(680, 580, 60, 60);

        jLabel19.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("N");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(620, 610, 60, 40);

        btnN.setBackground(new java.awt.Color(51, 255, 204));
        btnN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnN.setBorder(null);
        btnN.setBorderPainted(false);
        btnN.setContentAreaFilled(false);
        btnN.setMaximumSize(new java.awt.Dimension(60, 60));
        btnN.setMinimumSize(new java.awt.Dimension(60, 60));
        btnN.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnN);
        btnN.setBounds(620, 600, 60, 60);

        jLabel20.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Ñ");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(550, 600, 60, 70);

        btnÑ.setBackground(new java.awt.Color(51, 255, 204));
        btnÑ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnÑ.setBorder(null);
        btnÑ.setBorderPainted(false);
        btnÑ.setContentAreaFilled(false);
        btnÑ.setMaximumSize(new java.awt.Dimension(60, 60));
        btnÑ.setMinimumSize(new java.awt.Dimension(60, 60));
        btnÑ.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnÑ);
        btnÑ.setBounds(550, 600, 60, 60);

        jLabel21.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("O");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(480, 610, 60, 40);

        btnO.setBackground(new java.awt.Color(51, 255, 204));
        btnO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnO.setBorder(null);
        btnO.setBorderPainted(false);
        btnO.setContentAreaFilled(false);
        btnO.setMaximumSize(new java.awt.Dimension(60, 60));
        btnO.setMinimumSize(new java.awt.Dimension(60, 60));
        btnO.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnO);
        btnO.setBounds(480, 600, 60, 60);

        jLabel22.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("P");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(420, 580, 60, 40);

        btnP.setBackground(new java.awt.Color(51, 255, 204));
        btnP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnP.setBorder(null);
        btnP.setBorderPainted(false);
        btnP.setContentAreaFilled(false);
        btnP.setMaximumSize(new java.awt.Dimension(60, 60));
        btnP.setMinimumSize(new java.awt.Dimension(60, 60));
        btnP.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnP);
        btnP.setBounds(420, 570, 60, 60);

        jLabel23.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Q");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(360, 540, 60, 40);

        btnQ.setBackground(new java.awt.Color(51, 255, 204));
        btnQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnQ.setBorder(null);
        btnQ.setBorderPainted(false);
        btnQ.setContentAreaFilled(false);
        btnQ.setMaximumSize(new java.awt.Dimension(60, 60));
        btnQ.setMinimumSize(new java.awt.Dimension(60, 60));
        btnQ.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnQ);
        btnQ.setBounds(360, 530, 60, 60);

        jLabel24.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("R");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(330, 490, 50, 40);

        btnR.setBackground(new java.awt.Color(51, 255, 204));
        btnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnR.setBorder(null);
        btnR.setBorderPainted(false);
        btnR.setContentAreaFilled(false);
        btnR.setMaximumSize(new java.awt.Dimension(60, 60));
        btnR.setMinimumSize(new java.awt.Dimension(60, 60));
        btnR.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnR);
        btnR.setBounds(320, 480, 60, 60);

        jLabel25.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("S");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(300, 430, 50, 40);

        btnS.setBackground(new java.awt.Color(51, 255, 204));
        btnS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnS.setBorder(null);
        btnS.setBorderPainted(false);
        btnS.setContentAreaFilled(false);
        btnS.setMaximumSize(new java.awt.Dimension(60, 60));
        btnS.setMinimumSize(new java.awt.Dimension(60, 60));
        btnS.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnS);
        btnS.setBounds(290, 420, 60, 60);

        jLabel26.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("T");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(270, 370, 60, 40);

        btnT.setBackground(new java.awt.Color(51, 255, 204));
        btnT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnT.setBorder(null);
        btnT.setBorderPainted(false);
        btnT.setContentAreaFilled(false);
        btnT.setMaximumSize(new java.awt.Dimension(60, 60));
        btnT.setMinimumSize(new java.awt.Dimension(60, 60));
        btnT.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnT);
        btnT.setBounds(270, 360, 60, 60);

        jLabel27.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("U");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(270, 300, 60, 40);

        btnU.setBackground(new java.awt.Color(51, 255, 204));
        btnU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnU.setBorder(null);
        btnU.setBorderPainted(false);
        btnU.setContentAreaFilled(false);
        btnU.setMaximumSize(new java.awt.Dimension(60, 60));
        btnU.setMinimumSize(new java.awt.Dimension(60, 60));
        btnU.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnU);
        btnU.setBounds(270, 290, 60, 60);

        jLabel28.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("V");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(280, 220, 60, 60);

        btnV.setBackground(new java.awt.Color(51, 255, 204));
        btnV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnV.setBorder(null);
        btnV.setBorderPainted(false);
        btnV.setContentAreaFilled(false);
        btnV.setMaximumSize(new java.awt.Dimension(60, 60));
        btnV.setMinimumSize(new java.awt.Dimension(60, 60));
        btnV.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnV);
        btnV.setBounds(280, 220, 60, 60);

        jLabel29.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("W");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(310, 160, 60, 60);

        btnW.setBackground(new java.awt.Color(51, 255, 204));
        btnW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnW.setBorder(null);
        btnW.setBorderPainted(false);
        btnW.setContentAreaFilled(false);
        btnW.setMaximumSize(new java.awt.Dimension(60, 60));
        btnW.setMinimumSize(new java.awt.Dimension(60, 60));
        btnW.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnW);
        btnW.setBounds(310, 160, 60, 60);

        jLabel30.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("X");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(350, 110, 60, 60);

        btnX.setBackground(new java.awt.Color(51, 255, 204));
        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnX.setBorder(null);
        btnX.setBorderPainted(false);
        btnX.setContentAreaFilled(false);
        btnX.setMaximumSize(new java.awt.Dimension(60, 60));
        btnX.setMinimumSize(new java.awt.Dimension(60, 60));
        btnX.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnX);
        btnX.setBounds(350, 110, 60, 60);

        jLabel31.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Y");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(400, 70, 60, 60);

        btnY.setBackground(new java.awt.Color(51, 255, 204));
        btnY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnY.setBorder(null);
        btnY.setBorderPainted(false);
        btnY.setContentAreaFilled(false);
        btnY.setMaximumSize(new java.awt.Dimension(60, 60));
        btnY.setMinimumSize(new java.awt.Dimension(60, 60));
        btnY.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnY);
        btnY.setBounds(400, 70, 60, 60);

        jLabel32.setFont(new java.awt.Font("Rubik", 1, 55)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Z");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(470, 40, 60, 60);

        btnZ.setBackground(new java.awt.Color(51, 255, 204));
        btnZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnZ.setBorder(null);
        btnZ.setBorderPainted(false);
        btnZ.setContentAreaFilled(false);
        btnZ.setMaximumSize(new java.awt.Dimension(60, 60));
        btnZ.setMinimumSize(new java.awt.Dimension(60, 60));
        btnZ.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnZ);
        btnZ.setBounds(470, 40, 60, 60);

        btnE.setBackground(new java.awt.Color(51, 255, 204));
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/azul.png"))); // NOI18N
        btnE.setBorder(null);
        btnE.setBorderPainted(false);
        btnE.setContentAreaFilled(false);
        btnE.setMaximumSize(new java.awt.Dimension(60, 60));
        btnE.setMinimumSize(new java.awt.Dimension(60, 60));
        btnE.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(btnE);
        btnE.setBounds(780, 140, 60, 60);

        LogoArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/Pasapalabras04.gif"))); // NOI18N
        jPanel1.add(LogoArriba);
        LogoArriba.setBounds(890, 40, 450, 70);

        LogoCentro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoCentro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/game-over.png"))); // NOI18N
        LogoCentro1.setText("jLabel34");
        jPanel1.add(LogoCentro1);
        LogoCentro1.setBounds(810, 430, 540, 210);

        LogoCentro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/PasaPalabradown2.gif"))); // NOI18N
        LogoCentro.setText("jLabel34");
        jPanel1.add(LogoCentro);
        LogoCentro.setBounds(390, 180, 390, 90);

        lblFaltante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFaltante.setText("Preguntas Faltantes:");
        jPanel1.add(lblFaltante);
        lblFaltante.setBounds(40, 290, 220, 22);

        lblCorrectas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCorrectas.setForeground(new java.awt.Color(0, 255, 0));
        lblCorrectas.setText("Respuestas Correctas:");
        jPanel1.add(lblCorrectas);
        lblCorrectas.setBounds(40, 200, 250, 22);

        lblPasaste.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPasaste.setForeground(new java.awt.Color(204, 204, 0));
        lblPasaste.setText("Pasaste Palabra:");
        jPanel1.add(lblPasaste);
        lblPasaste.setBounds(40, 260, 230, 22);

        lblErronea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErronea.setForeground(new java.awt.Color(204, 0, 0));
        lblErronea.setText("Respuestas Erróneas: ");
        jPanel1.add(lblErronea);
        lblErronea.setBounds(40, 230, 230, 22);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication30/fondoazul.jpg"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 20, 1420, 720);

        btnNADA.setText("jButton1");
        jPanel1.add(btnNADA);
        btnNADA.setBounds(30, 430, 73, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    numero=0;
     this.LogoCentro1.setVisible(false);
            this.LogoArriba.setVisible(true);
            this.LogoCentro.setVisible(false);
    this.lblpregunta.setVisible(true);
    this.jLabel13.setVisible(true);
    this.txtRespuesta.setVisible(true);
    this.jLabel2.setVisible(true);
    this.btnResponder.setVisible(true);
    this.btnPasaPalabra.setVisible(true);    
    this.btnIniciar.setVisible(false);
    this.btnFin.setVisible(true);
    correctas = 0; erroneas = 0; pasaste = 0; 
    this.lblFaltante.setText("Preguntas Faltantes: 27");
    this.lblCorrectas.setText("Respuestas Correctas: "+String.valueOf(correctas));    
    this.lblErronea.setText("Respuestas Erróneas: "+String.valueOf(erroneas));   
    this.lblPasaste.setText("Pasaste Palabra: "+String.valueOf(pasaste));       
//    MM.btncolor(cuales(1), "amarillo");
    lblpregunta.setText(preguntas[numero][0]);
    MM.cartel(lblpregunta);
    MM.setSegundos(180);
    MM.tiempo(btnTiempo);
    
        for (int i = 0; i < 27; i++) {
            MM.btncolor(cuales(i), "azul");
        }
      MM.btncolor(cuales(numero), "actual");
   
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        this.LogoCentro1.setVisible(true);
        this.LogoCentro.setVisible(true);
        this.LogoArriba.setVisible(false);
        this.lblpregunta.setVisible(false);
        this.jLabel13.setVisible(false);
        this.txtRespuesta.setVisible(false);
        this.jLabel2.setVisible(false);
        this.btnResponder.setVisible(false);
        this.btnPasaPalabra.setVisible(false);
        lblpregunta.setText("");
        MM.setSegundos(0);
        this.btnIniciar.setVisible(true);
        this.btnFin.setVisible(false);
        this.btnTiempo.setText("180");
    }//GEN-LAST:event_btnFinActionPerformed

    private void btnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTiempoActionPerformed

    private void txtRespuestaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRespuestaFocusGained
        this.txtRespuesta.setText("");     
    }//GEN-LAST:event_txtRespuestaFocusGained

    private void txtRespuestaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRespuestaFocusLost
//        this.txtRespuesta.setText("Tu respuesta aquí...");
    }//GEN-LAST:event_txtRespuestaFocusLost

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed

    }//GEN-LAST:event_btnDActionPerformed

    private void btnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderActionPerformed
     String respuesta;
     respuesta = this.txtRespuesta.getText();
     if(Integer.parseInt(this.btnTiempo.getText())<=1){
         this.LogoCentro1.setVisible(true);
     }
     
     respuesta = respuesta.trim();
     this.txtRespuesta.setText("Tu respuesta aquí..."); 
     if(preguntas[numero][1].equalsIgnoreCase(respuesta)){
         MM.aplausos();
         MM.btncolor(cuales(numero), "verde");
          preguntas[numero][2] = "verde";
          correctas++;
             this.lblCorrectas.setText("Respuestas Correctas: "+String.valueOf(correctas));          
     }  else {
         MM.waverror();
        MM.btncolor(cuales(numero), "rojo"); 
         preguntas[numero][2] = "rojo";
         erroneas++;
       this.lblErronea.setText("Respuestas Erróneas: "+String.valueOf(erroneas));   
     }     
  numero++; 
        this.lblFaltante.setText("Preguntas Faltantes: "+String.valueOf(27-numero));
          
    if(numero >=27 || "0".equals(this.btnTiempo.getText())){
        this.btnFin.doClick();
    }
        MM.btncolor(cuales(numero), "actual");
    lblpregunta.setText(preguntas[numero][0]);
    MM.cartel(lblpregunta);
    }//GEN-LAST:event_btnResponderActionPerformed

    private void btnPasaPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasaPalabraActionPerformed
        MM.btncolor(cuales(numero), "amarillo");
         preguntas[numero][2] = "amarillo";
      numero++;
        pasaste++;
              this.lblFaltante.setText("Preguntas Faltantes: "+String.valueOf(27-numero));
             this.lblPasaste.setText("Pasaste Palabra: "+String.valueOf(pasaste));
               
    if(numero >=27 || "0".equals(this.btnTiempo.getText())){
        this.btnFin.doClick();
    }
              MM.btncolor(cuales(numero), "actual");
        lblpregunta.setText(preguntas[numero][0]);
        MM.cartel(lblpregunta);
    }//GEN-LAST:event_btnPasaPalabraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

      public JButton cuales(int numero){
        switch(numero){
            case 0:
                return btnA;
            case 1:
                return btnB;
            case 2:
                return btnC; 
            case 3:
                return btnD;                       
            case 4:
                return btnE;  
            case 5:
                return btnF; 
            case 6:
                return btnG; 
            case 7:
                return btnH; 
            case 8:
                return btnI; 
            case 9:
                return btnJ; 
            case 10:
                return btnK; 
            case 11:
                return btnL; 
             case 12:
                return btnM; 
             case 13:
                return btnN; 
             case 14:
                return btnÑ; 
             case 15:
                return btnO; 
             case 16:
                return btnP; 
             case 17:
                return btnQ; 
             case 18:
                return btnR; 
             case 19:
                return btnS; 
             case 20:
                return btnT; 
             case 21:
                return btnU; 
             case 22:
                return btnV; 
             case 23:
                return btnW; 
             case 24:
                return btnX; 
             case 25:
                return btnY; 
             case 26:
                return btnZ; 
            default:
                return btnNADA;
        }
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LogoArriba;
    private javax.swing.JLabel LogoCentro;
    private javax.swing.JLabel LogoCentro1;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnNADA;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnPasaPalabra;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnResponder;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnTiempo;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JButton btnÑ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorrectas;
    private javax.swing.JLabel lblErronea;
    private javax.swing.JLabel lblFaltante;
    private javax.swing.JLabel lblPasaste;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
